window.onload = function() {
	var functions = [
	  "abs",
		"acos",
		"alpha",
		"angleMode",
		"append",
		"applyMatrix",
		"arc",
		"arrayCopy",
		"asin",
		"atan",
		"atan2",
		"background",
		"beginContour",
		"beginShape",
		"bezier",
		"bezierDetail",
		"bezierPoint",
		"bezierTangent",
		"bezierVertex",
		"blend",
		"blendMode",
		"blue",
		"brightness",
		"ceil",
		"clear",
		"color",
		"colorMode",
		"concat",
		"constrain",
		"copy",
		"cos",
		"createCanvas",
		"createGraphics",
		"createImage",
		"createVector",
		"cursor",
		"curve",
		"curveDetail",
		"curvePoint",
		"curveTangent",
		"curveVertex",
		"day",
		"degrees",
		"dist",
		"draw",
		"ellipse",
		"ellipseMode",
		"endContour",
		"endShape",
		"exp",
		"fill",
		"filter",
		"floor",
		"frameCount",
		"frameRate",
		"fullscreen",
    "get",
		"green",
		"hour",
		"hue",
		"image",
		"imageMode",
		"join",
		"keyPressed",
		"keyReleased",
		"keyTyped",
		"lerp",
		"lerpColor",
		"line",
		"loadImage",
		"loadJSON",
		"loadPixels",
		"loadStrings",
		"loadTable",
		"loadXML",
		"log",
		"loop",
		"mag",
		"map",
		"match",
		"matchAll",
		"max",
		"millis",
		"min",
		"minute",
		"month",
		"mouseClicked",
		"mouseDragged",
		"mouseMoved",
		"mousePressed",
		"mouseReleased",
		"mouseWheel",
		"nf",
		"nfc",
		"nfp",
		"nfs",
		"noCursor",
		"noFill",
		"noise",
		"noiseDetail",
		"noiseSeed",
		"noLoop",
		"norm",
		"noSmooth",
		"noStroke",
		"noTint",
		"point",
		"pop",
		"pow",
		"preload",
		"print",
		"push",
		"quad",
		"quadraticVertex",
		"radians",
		"random",
		"randomGaussian",
		"randomSeed",
		"rect",
		"rectMode",
		"red",
		"redraw",
		"remove",
		"resetMatrix",
		"reverse",
		"rotate",
		"saturation",
		"saveJSON",
		"saveStrings",
		"saveTable",
		"scale",
		"second",
    "set",
		"setup",
		"shearX",
		"shearY",
		"shorten",
		"sin",
		"smooth",
		"sort",
		"splice",
		"split",
		"sq",
		"sqrt",
		"stroke",
		"strokeCap",
		"strokeJoin",
		"strokeWeight",
		"subset",
		"tan",
		"text",
		"textAlign",
		"textFont",
		"textHeight",
		"textLeading",
		"textSize",
		"textStyle",
		"textWidth",
		"tint",
		"touchEnded",
		"touchMoved",
		"touchStarted",
		"translate",
		"triangle",
		"trim",
		"updatePixels",
		"vertex",
		"year",
	];

  functions.sort(function(a, b){
    return a.length - b.length;
  });

  var pres = document.querySelectorAll('.pln');
	for(var i=pres.length;i--;) {
		var str = pres[i].innerText;
    if(!str) continue;

    var unmatched = true;
    for(var j=functions.length;j--;) {
      if(unmatched && str.match(functions[j])) {
        var hyperlink = '<a href="http://p5js.org/reference/#/p5/' + functions[j] + '" target="_blank">' + functions[j] + "</a>";
        str = str.replace(functions[j], hyperlink);
        unmatched = false;
      }
		}

		pres[i].innerHTML = str;
	}
}